---
title: "Lars Schöbitz's CV"
author: Lars Schöbitz
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1wdhJRl-BhwtJ6RiuM5MDAAJgeEpWK1uDr_kBxImVJrM/edit#gid=0",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
# datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _lse.de/cv_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://raw.githubusercontent.com/larnsce/cv/master/lars_schoebitz_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available [on github.com/larnsce/cv](https://github.com/larnsce/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Lars Schöbitz {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```

Me {data-icon=user-circle}
--------------------------------------------------------------------------------

```{r}

CV %>% print_section("personal")

```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Work Experience {data-icon=laptop}
--------------------------------------------------------------------------------
::: aside
```{r}
CV %<>% print_text_block('sanitation_rights')
```
:::

```{r}
CV %<>% print_section('work_experience')
```


Teaching Experience {data-icon=briefcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching')
```

Pro Bono {data-icon=briefcase}
--------------------------------------------------------------------------------

::: aside
I am passionate about teaching coding with R to novel users.
:::

```{r}
CV %>% print_section('pro_bono_work')
```


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
# CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
# CV %<>% print_section('teaching_positions')
```


Publications {data-icon=book}
--------------------------------------------------------------------------------

::: aside
I support open science principles.
:::

```{r}
CV %>% 
  print_section('publications')
```

Technical Reports {data-icon=bookmark}
--------------------------------------------------------------------------------

::: aside
I strive for efficiency and approach life with 'All or Nothing'.
:::

```{r}
CV %>% 
  print_section('technical_reports')
```


Sandec News Article {data-icon=book-open}
--------------------------------------------------------------------------------

::: aside
I have a mindset of learning from failures and am a signatory of the [Nakuru Accord](https://wash.leeds.ac.uk/failing-better-in-the-wash-sector/)
:::

```{r}
CV %>% 
  print_section('sandec_news')
```

Conferences & Seminars {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
I am optimistic, direct, patient and empathetic.
:::


```{r}
CV %>% 
  print_section('conferences_seminars')
```

References {data-icon=address-book}
--------------------------------------------------------------------------------

```{r}

CV %>% 
  print_section('references')

```
